import mongoose from "mongoose";
const Schema = mongoose.Schema;

const facilitySchema = new Schema({
  school: { type: Schema.Types.ObjectId, ref: "School", required: true },
  blocksOfClassroom: Number,
  numOfClassrooms: Number,
  numOfUsedClassrooms: Number,
  numOfbadClassrooms: Number,
  eccdeClassrooms: Number,
  primaryClassrooms: Number,
  ubeJssClassroom: Number,
  pitToilet: Number,
  waterCloset: Number,
  vipToilet: Number,
  badPitToilet: Number,
  badWaterCloset: Number,
  badVipToilet: Number,
  goodPitToilet: Number,
  goodWaterCloset: Number,
  goodVipToilet: Number,
  mPitToilet: Number,
  mWaterCloset: Number,
  mVipToilet: Number,
  fence: String,
  agricFarm: String,
  sportFacility: String,
  eccdeVentilation: String,
  eccdeVenComment: String,
  primaryVentilation: String,
  primaryVenComment: String,
  ubeJssVentilation: String,
  ubeJssVenComment: String,
  eccdeChairs: Number,
  eccdeTables: Number,
  primaryChairs: Number,
  primaryTables: Number,
  ubeJssChairs: Number,
  ubeJssTables: Number,
  teachersChairs: Number,
  teachersTables: Number,
  blackboard: String,
  numOfBlackboards: Number,
  whiteboard: String,
  numOfWhiteboards: String,
  textbook: String,
  lessonNotes: String,
  curriculum: String,
  eccdeLearningMaterials: String,
  eccdeToys: Number,
  eccdeBricks: Number,
  eccdeCountingMaterials: Number,
  capturedBy: String,
  dateCreated: { type: Date, default: Date.now },
});

export const Facilities = mongoose.model("Facilities", facilitySchema);
