import mongoose from "mongoose";
const Schema = mongoose.Schema;

const facilitySchema = new Schema({
  school: { type: Schema.Types.ObjectId, ref: "School", required: true },
  toilet: String,
  toiletComment: String,
  fence: String,
  fenceComment: String,
  agricFarm: String,
  agricFarmComment: String,
  sportFacility: String,
  sportFacilityComment: String,
  schoolName: String,
  blocksOfClassroom: String,
  eccdeClassroom: String,
  eccdeClassroomComment: String,
  primaryClassroom: String,
  primaryClassroomComment: String,
  ubeJssClassroom: String,
  ubeJssClassroomComment: String,
  eccdeVentilation: String,
  eccdeVenComment: String,
  primaryVentilation: String,
  eccdePriComment: String,
  ubeJssVentilation: String,
  ubeJssVenComment: String,
  eccdeFurniture: String,
  eccdeFurnitureComment: String,
  primaryFurniture: String,
  primaryFurnitureComment: String,
  ubeJssFurniture: String,
  ubeJssFurnitureComment: String,
  teachersFurniture: String,
  teachersFurnitureComment: String,
  blackboard: String,
  blackboardComment: String,
  textbook: String,
  textbookComment: String,
  whiteboard: String,
  whiteboardComment: String,
  lessonNoyes: String,
  lessonNotesComment: String,
  curriculum: String,
  curriculumComment: String,
  eccdeLearningMaterials: String,
  eccdeLmComment: String,
  capturedBy: String,
});

export const Facilities = mongoose.model("Facilities", facilitySchema);
